---
title: "CV"
about:
  template: solana
---

## **EDUCATION**

Incoming Post-Grad \@ University of Edinburgh MSc in Geographical Information Science and Earth Observation (2026-27)

University of Oregon \| Eugene, OR B.S in Spatial Data Science & Technology \| Sept 2022 - June 2026

University of Oregon \| Eugene, OR B.S in Anthropology \| Sept 2022 - June 2026

## **FIELD, LAB, AND RESEARCH EXPERIENCE**

**University of Oregon Archaeobotany Lab, Eugene, Oregon \| October 2025 - June 2026**

*Supervisor*: Dr. Gyoung-Ah Lee

Volunteered in this lab to gain experience with starch and microbotanical analysis. Learned how to complete steps of starch analysis on archaeological ceramics, including ceramics from Project P’Teah to contribute to our understanding of Prasat Baset.

**Student Research Assistant, Project P’Teah, Battambang, Cambodia \| June 2024 - June 2026**

*Supervisor*: Dr. Alison Carter

Joined Project P’Teah as a student research assistant for five weeks in Battambang, Cambodia (specifically focusing on the temple, Prasat Baset). Duties with data collection, cataloging, preliminary analysis, photography, and measurements. Gained knowledge regarding ceramics in Cambodia and ceramic identification.

**University of Oregon Island and Coastal Archaeology Lab, Eugene, Oregon \| January 2024 - June 2024**

*Supervisor:* Dr. Scott Fitzpatrick

Duties included cataloging artifacts, maintained a database, and organized the collections spanning 25 years of archaeological work. Participated in a poster session at the Undergraduate Research Symposium at the University of Oregon regarding the collections of shells, bones, and other materials.

## **JOB EXPERIENCE**

**Tour Guide, University of Oregon Clark Honors College, Eugene, Oregon \| January 2023- June 2026**

Duties include leading tours and occasionally presenting in larger settings. Increased confidence regarding public speaking and sharing information effectively. Presented in larger settings of up to 100 people at Duck Days events for prospective Clark Honors College students.

**Archaeology Intern, WSP, Riverside, CA \| June 2025- August 2025**

Joined WSP to assist with Cultural Resource Management team in Southern California. Learned CRM processes and legal implications of CRM. Increased understanding of application of laws and procedures expected nationally and statewide in California. Assisted with tribal consultation.

**Barista, Ovation Coffee and Tea, Portland, Oregon \| June 2022 - August 2023**

Began with little coffee experience, worked up to being a barista and could make the wide range of drinks on the menu. Gained experience with customer service, time management, and teamwork.

## **RELEVANT COURSEWORK**

GIS I, GIS II, Advanced GIS with Python, Geographic Data Analysis, Remote Sensing I, Remote Sensing II, Web Mapping, Spatial Demography, Geographic Data Analysis, Changing Landscapes, Statistics, Statistical Analysis for Biological Anthropology, Introduction to Python, Protein Wars, Nutritional Anthropology, Food in World History, Food Science and Sustainability, Health, Food, and Culture, Ancient Psychoactive Substances, Southeast Asian Archaeology.

## **ADDITIONAL EXPERIENCE**

**2024 Food, Culture, and Sustainability, University of Oregon, Siena, Italy**

Took four courses at the University of Oregon center in Siena, Italy. Explored farming, food, and sustainability with an emphasis on Italian culture throughout the 12-week long program.

**2023-2024 Emerging Leadership Project, University of Oregon, Eugene, Oregon**

A year-long program involving weekly meetings and volunteer hours. Gained knowledge and skills to work effectively within teams to contribute my unique leadership skills and style.

## **AWARDS AND SCHOLARSHIPS**

2026 Anthropology Undergraduate Paper of the Year Award

2026 Asian Studies Award (Undergraduate)

2022-2026 Presidential Scholarship, University of Oregon

2022-2026 Summit Scholarship, University of Oregon

2022-2026 IB Exemplar Scholarship, University of Oregon

2025 Anthropology Undergraduate Research and Conference Participation Award

2024 Hannibal Nelsen Scholarship, University of Oregon

2022 Full IB Diploma, Lincoln High School

## **PRESENTATIONS**

2026 Society for American Archaeology Conference (San Francisco, CA)

2026 Undergraduate Research Symposium Asian Studies Event \@ UO

2025 Society for American Archaeology Conference (Denver, CO)

2025 Undergraduate Research Symposium \@ UO

2024 Undergraduate Research Symposium \@ UO

## **MEMBERSHIPS**

2026 Phi Beta Kappa

2025 - 2026 Society for American Archaeology
