---
title: "Cost of Living in San Francisco "
about: 
  template: solana
---

```{r}
#| message: false
#| code-fold: true

library(tidycensus) 
library(sf)
library(tidyverse)
library(tigris)
library(patchwork)
library(spdep)
library(tmap)
library(mapview)

```

```{r}
#| message: false
#| code-fold: true

sf_var <- c(
  med_gross_rent = "B25064_001",
  med_income = "B19013_001",
  med_housing_cost = "B25105_001")

```

```{r}
#| message: false
#| code-fold: true
#| results: hide

# SF data
sf_data <- get_acs(
  geography = "tract", 
  variables = sf_var,
  state = "CA", 
  county = "San Francisco", 
  output = "wide",
  geometry = TRUE, 
  year = 2020
) %>%
  st_transform(7131)|> # filtering out islands
  filter(!GEOID %in% c(
    "06075980401",  # Farallon Islands
    "06075017902",  # Treasure Island / Yerba Buena
    "06075017901",  # Treasure Island
    "06075017903",  # Treasure Island 
    "06075980300"   # water tract
  )) |>
  filter(!st_is_empty(geometry)) |>
  filter(st_is_valid(geometry))



```

```{r}
#| message: false
#| code-fold: true

# mapping median rent estimate 
med_rent_map <- ggplot(sf_data, aes(fill = med_gross_rentE)) +
  geom_sf(color = NA) +
  scale_fill_viridis_c(option = "mako",
                       labels = scales::label_dollar()) +
  theme(text = element_text(family = "Verdana")) +
  theme_void() +
  labs(fill = "Median Gross Rent in San Francisco, CA",
       caption = "Source: 2020 5-Year ACS, US Census Bureau")

med_rent_map

```

```{r}
# mapping clusters of high low and high rent in San Francisco 
# weights matrix

sf_data <- sf_data |> filter(!is.na(med_gross_rentE))

neighbors <- poly2nb(sf_data, queen = TRUE)
summary(neighbors)

sf_data[card(neighbors) == 0, ] |> select(GEOID, NAME)

weights <- nb2listw(neighbors, style = "W", zero.policy = TRUE)
weights$weights[[1]]

neighbors[[1]]

sf_data$lag_estimate <- lag.listw(weights, sf_data$med_gross_rentE)


# For Gi*, re-compute the weights with `include.self()`
localg_weights <- nb2listw(include.self(neighbors))

sf_data$localG <- as.numeric(localG(sf_data$med_gross_rentE, localg_weights))


```

```{r}
#| message: false
#| code-fold: true

# Local Gi* Statistic plot
tmap_mode("view")

tm_shape(sf_data) +
  tm_polygons(
    fill = "localG",
    fill.scale = tm_scale_continuous(
      values = "brewer.rd_yl_bu"
    ),
    fill.legend = tm_legend(title = "Local Gi* Statistic"),
    col = NA
  ) +
  tm_basemap("CartoDB.Positron") +
  tm_title("Local Gi* Statistic in San Francisco, CA")

```

```{r}
#| message: false
#| code-fold: true

# Map of Local Gi scores w/spatial clusters highlighted
sf_data <- sf_data %>%
mutate(hotspot = case_when(
localG >= 2.56 ~ "High cluster",
localG <= -2.56 ~ "Low cluster",
TRUE ~ "Not significant"
))

tmap_mode("view")

tm_shape(sf_data) +
  tm_polygons(
    fill = "hotspot",
    fill.scale = tm_scale_categorical(
      values = c("High cluster" = "red", "Low cluster" = "blue", "Not significant" = NA)
    ),
    fill.legend = tm_legend(title = "Rental Clusters"),
    col = NA,
    col_alpha = 0.5
  ) +
  tm_basemap("CartoDB.Positron") +
  tm_title("Areas with High & Low Rent Clusters in San Francisco, CA")

```

```{r}
#| message: false
#| code-fold: true

vacancy_vars <- c(vacant = "B25004_001", 
                  total = "B25002_001")

recent_vacancy <- get_acs(
  geography = "tract", 
  variables = vacancy_vars,
  state = "CA", 
  county = "San Francisco", 
  geometry = TRUE, 
  output = "wide", 
  year = 2024
) %>%
  st_transform(7131)|> # filtering out islands
  filter(!GEOID %in% c(
    "06075980401",  # Farallon Islands
    "06075017902",  # Treasure Island / Yerba Buena
    "06075017901",  # Treasure Island
    "06075017903",  # Treasure Island 
    "06075980300"   # water tract
  )) |>
  filter(!st_is_empty(geometry)) |>
  filter(st_is_valid(geometry)) 

sf_vacancy_rate <- recent_vacancy %>%
 mutate(vacancy_rate = vacantE/totalE)
 

# mapping vacancy rate
tmap_mode("view")

vacancy_map <- tm_shape(sf_vacancy_rate |> filter(!is.na(vacancy_rate))) +
  tm_polygons(
    fill = "vacancy_rate",
    fill.scale = tm_scale_continuous(
      values = "brewer.gn_bu"
    ),
  fill.legend = tm_legend(title = "Vacancy Rate", reverse = TRUE),
    col = NA
  ) +
  tm_basemap("CartoDB.Positron") +
  tm_title("Vacant Housing Units in San Francisco, CA")

vacancy_map
```
